version: '2'
services:
  pay-admin:
    image: pay/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  pay-api:
    image: pay/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev